name: RenteraCore
version: 1.0
main: gg.aquatic.renteraislands.paper.RenteraIslands
api-version: 1.20
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:2.0.0"
depend:
  - Vault
  - PlaceholderAPI
  - SlimeWorldManager